version: '3.3'
services:
        web:
                image: php:7.3-apache
                container_name: php7
                volumes:
                        - ./apps:/var/www/html/
                ports:
                        - 8000:80

